branches:
  only:
  - master
language: go
go:
  - 1.12.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.67.0/hugo_extended_0.67.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.67.0_Linux-64bit.deb

#Deploy non nécessaire suite à bascule vers netlify
#before_script:
#  - chmod +x ./_deploy.sh

script:
  - hugo

#Deploy non nécessaire suite à bascule vers netlify
#deploy:
#  provider: script
#  script: ./_deploy.sh
#  skip_cleanup: true
